name: Compilación y pruebas proyecto C#
on: push
jobs:
  Compilacion:
    runs-on: ubuntu-latest
    environment: PRUEBAS
    steps:
      - run: echo "El secreto Google es ${{ secrets.SECRET_PRUEBA }}"
      - uses: actions/checkout@v2
      - name: Compilamos
        run: dotnet build
      - name: Ejecutamos las pruebas
        run: dotnet test
      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: Nuevo Release
          
